version: "3.8"

services:
  localstack:
    image: "localstack/localstack:latest"
    container_name: "my-localstack"
    ports:
      - "4566:4566"
    environment:
      SERVICES: "dynamodb"
      DEBUG: 1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - "local"

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    container_name: "dynamodb-viewer"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    depends_on:
      - "localstack"
    networks:
      - "local"

networks:
  local:
    driver: "bridge"